language: php
sudo: false

matrix:
  include:
    # Use the newer stack for HHVM as HHVM does not support Precise anymore
    - php: hhvm-nightly
      sudo: required
      dist: trusty
      group: edge
    - php: 5.4
      env: lowest=1
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ] || [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then phpenv config-rm xdebug.ini; fi;'
  - if [ "$lowest" = "1" ]; then composer update --prefer-lowest --prefer-stable; else composer install; fi;

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ] && [ "$TRAVIS_PHP_VERSION" != "5.4" ] && [ "$TRAVIS_PHP_VERSION" != "5.5" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover tests; else vendor/bin/phpunit; fi;'

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ] && [ "$TRAVIS_PHP_VERSION" != "5.4" ] && [ "$TRAVIS_PHP_VERSION" != "5.5" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ] && [ "$TRAVIS_PHP_VERSION" != "5.4" ] && [ "$TRAVIS_PHP_VERSION" != "5.5" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
